version: "3.8"

services:
  service:
    container_name: ntrca_frontend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./:/home/ntrca_frontend
    ports:
      - "3033:3000"
    tty: true
    networks:
      - server

networks:
  server:
    driver: bridge
