export default {
  NEW_MPO_APPLICATION: "NEW_MPO_APPLICATION",
  BED_SCALE: "BED_SCALE",
  CORRECTION: "CORRECTION",
  INDEX_RELEASE: "INDEX_RELEASE",
  TRANSFER: "TRANSFER",
  UPPER_GRADE: "UPPER_GRADE",
  ARREAR: "ARREAR",
};
